### PR TITLE
Update 3.0.0 binaries to 3.0.0-beta-1

### PR DESCRIPTION
**Pull request by trask**
I got the 3.0.0-beta-1 binaries from

* http://search.maven.org/remotecontent?filepath=com/google/protobuf/protoc/3.0.0-beta-1/protoc-3.0.0-beta-1-linux-x86_64.exe
* http://search.maven.org/remotecontent?filepath=com/google/protobuf/protoc/3.0.0-beta-1/protoc-3.0.0-beta-1-osx-x86_64.exe
* http://search.maven.org/remotecontent?filepath=com/google/protobuf/protoc/3.0.0-beta-1/protoc-3.0.0-beta-1-windows-x86_32.exe

Tested on Windows, Linux and OSX.

### CODE REVIEW

**Comment by xuwei-k** [comment]
+1

**Comment by os72** [comment]
Thanks guys, looking into it. Does Google now provide the binaries?

**Comment by trask** [comment]
Yes, even better, the binaries are already in maven central, so maybe could make the plugin point to the official binaries as dependencies somehow

http://search.maven.org/#search%7Cga%7C1%7Cprotobuf%20protoc

**Comment by os72** [comment]
I pulled the change, will sanity check and release it. Thanks

**Comment by os72** [comment]
Binaries (linux/mac) seem built differently from what I used to do, larger and cannot strip them, but they're working for me as well

**Comment by os72** [comment]
Released protoc-jar-3.0.0-b1

**Pull request merged**
