### PR TITLE
Strip binaries for FreeBSD.

### PR DESCRIPTION
**Pull request by kjopek**
Just make binaries smaller.

### CODE REVIEW

**Comment by os72** [comment]
Great! Binaries are on sonatype SNAPSHOT now, could give it a try?
`java -jar target/protoc-jar-3.4.0.1-SNAPSHOT.jar --version -v2.4.1-SNAPSHOT`

**Comment by kjopek** [comment]
Well, we have still problem with test on support_unbundled branch:
```
▶ mvn install
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building protoc-jar 3.4.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ protoc-jar ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ protoc-jar ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 13 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.0:compile (default-compile) @ protoc-jar ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to /tmp/protoc-jar/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ protoc-jar ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.0:testCompile (default-testCompile) @ protoc-jar ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /tmp/protoc-jar/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ protoc-jar ---
[INFO] Surefire report directory: /tmp/protoc-jar/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.github.os72.protocjar.ProtocTest
protoc-jar-test: testRunProtocCompile
protoc-jar: protoc version: 2.4.1, detected platform: freebsd-x86_64 (freebsd/amd64)
protoc-jar: embedded: bin/2.4.1/protoc-2.4.1-freebsd-x86_64.exe
protoc-jar: executing: [/tmp/protocjar5229173722260020923/bin/protoc.exe, --java_out=target/test-protoc, src/test/resources/PersonSchema.proto]
protoc-jar-test: testRunProtocBasic
protoc-jar: protoc version: 3.4.0, detected platform: freebsd-x86_64 (freebsd/amd64)
protoc-jar: embedded: bin/3.4.0/protoc-3.4.0-freebsd-x86_64.exe
protoc-jar: executing: [/tmp/protocjar8933305316694915191/bin/protoc.exe, --version]
libprotoc 3.4.0
protoc-jar: protoc version: 2.4.1, detected platform: freebsd-x86_64 (freebsd/amd64)
protoc-jar: embedded: bin/2.4.1/protoc-2.4.1-freebsd-x86_64.exe
protoc-jar: executing: [/tmp/protocjar1905935878100322451/bin/protoc.exe, --version]
libprotoc 2.4.1
protoc-jar: protoc version: 2.5.0, detected platform: freebsd-x86_64 (freebsd/amd64)
protoc-jar: embedded: bin/2.5.0/protoc-2.5.0-freebsd-x86_64.exe
protoc-jar: executing: [/tmp/protocjar4460972330472141796/bin/protoc.exe, --version]
libprotoc 2.5.0
protoc-jar: protoc version: 2.6.1, detected platform: freebsd-x86_64 (freebsd/amd64)
protoc-jar: embedded: bin/2.6.1/protoc-2.6.1-freebsd-x86_64.exe
protoc-jar: executing: [/tmp/protocjar1546582180187477480/bin/protoc.exe, --version]
libprotoc 2.6.1
protoc-jar: protoc version: 3.4.0, detected platform: freebsd-x86_64 (freebsd/amd64)
protoc-jar: embedded: bin/3.4.0/protoc-3.4.0-freebsd-x86_64.exe
protoc-jar: executing: [/tmp/protocjar718393562578155573/bin/protoc.exe, --version]
libprotoc 3.4.0
protoc-jar-test: testRunProtocCompileShade
protoc-jar: protoc version: 2.4.1, detected platform: freebsd-x86_64 (freebsd/amd64)
protoc-jar: embedded: bin/2.4.1/protoc-2.4.1-freebsd-x86_64.exe
protoc-jar: executing: [/tmp/protocjar336390419524005397/bin/protoc.exe, --java_out=target/test-protoc-shaded-241, src/test/resources/PersonSchema.proto]
protoc-jar: shading (version 2.4.1): target/test-protoc-shaded-241
protoc-jar: protoc version: 2.5.0, detected platform: freebsd-x86_64 (freebsd/amd64)
protoc-jar: embedded: bin/2.5.0/protoc-2.5.0-freebsd-x86_64.exe
protoc-jar: executing: [/tmp/protocjar3672567206894615326/bin/protoc.exe, --java_out=target/test-protoc-shaded-250, src/test/resources/PersonSchema.proto]
protoc-jar: shading (version 2.5.0): target/test-protoc-shaded-250
protoc-jar: protoc version: 2.6.1, detected platform: freebsd-x86_64 (freebsd/amd64)
protoc-jar: embedded: bin/2.6.1/protoc-2.6.1-freebsd-x86_64.exe
protoc-jar: executing: [/tmp/protocjar8909622438086302394/bin/protoc.exe, --java_out=target/test-protoc-shaded-261, src/test/resources/PersonSchema.proto]
protoc-jar: shading (version 2.6.1): target/test-protoc-shaded-261
protoc-jar-test: testRunProtocDownload
protoc-jar: protoc version: com.google.protobuf:protoc:3.0.0, detected platform: freebsd-x86_64 (freebsd/amd64)
protoc-jar-test: testStdTypes
protoc-jar: protoc version: 2.6.1, detected platform: freebsd-x86_64 (freebsd/amd64)
protoc-jar: embedded: bin/2.6.1/protoc-2.6.1-freebsd-x86_64.exe
protoc-jar: executing: [/tmp/protocjar877284068186826421/bin/protoc.exe, -I/tmp/protocjar877284068186826421/include, -I., --java_out=target/test-protoc-stdtypes, src/test/resources/StdTypeExample2.proto]
protoc-jar: protoc version: 3.4.0, detected platform: freebsd-x86_64 (freebsd/amd64)
protoc-jar: embedded: bin/3.4.0/protoc-3.4.0-freebsd-x86_64.exe
protoc-jar: executing: [/tmp/protocjar659668012798883393/bin/protoc.exe, -I/tmp/protocjar659668012798883393/include, -I., --java_out=target/test-protoc-stdtypes, src/test/resources/StdTypeExample3.proto]
Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.948 sec <<< FAILURE!
testRunProtocDownload(com.github.os72.protocjar.ProtocTest)  Time elapsed: 0.505 sec  <<< ERROR!
java.io.FileNotFoundException: http://central.maven.org/maven2/com/google/protobuf/protoc/3.0.0/protoc-3.0.0-freebsd-x86_64.exe
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at com.github.os72.protocjar.Protoc.downloadFile(Protoc.java:322)
	at com.github.os72.protocjar.Protoc.downloadProtoc(Protoc.java:265)
	at com.github.os72.protocjar.Protoc.extractProtoc(Protoc.java:218)
	at com.github.os72.protocjar.Protoc.extractProtoc(Protoc.java:182)
	at com.github.os72.protocjar.Protoc.runProtoc(Protoc.java:71)
	at com.github.os72.protocjar.ProtocTest.testRunProtocDownload(ProtocTest.java:57)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)


Results :

Tests in error: 
  testRunProtocDownload(com.github.os72.protocjar.ProtocTest): http://central.maven.org/maven2/com/google/protobuf/protoc/3.0.0/protoc-3.0.0-freebsd-x86_64.exe
```

**Comment by os72** [comment]
Yes. I see why you had added that condition. But could you build via `mvn clean install -DskipTests` and try the cmd line?

There is also the subtle difference that in test it finds the files locally ("embedded"), but in release it would attempt to download (for freebsd)

**Comment by kjopek** [comment]
Ok, here is the test:
```
▶ for version in 2.4.1-SNAPSHOT 2.5.0-SNAPSHOT 2.6.1-SNAPSHOT; do
java -jar target/protoc-jar-3.4.0.1-SNAPSHOT.jar --version -v"${version}"
done;
java.lang.IllegalArgumentException: Unsupported version: -v2.4.1-SNAPSHOT
	at com.github.os72.protocjar.ProtocVersion.getVersion(ProtocVersion.java:31)
	at com.github.os72.protocjar.Protoc.getVersion(Protoc.java:305)
	at com.github.os72.protocjar.Protoc.runProtoc(Protoc.java:55)
	at com.github.os72.protocjar.Protoc.main(Protoc.java:43)
java.lang.IllegalArgumentException: Unsupported version: -v2.5.0-SNAPSHOT
	at com.github.os72.protocjar.ProtocVersion.getVersion(ProtocVersion.java:31)
	at com.github.os72.protocjar.Protoc.getVersion(Protoc.java:305)
	at com.github.os72.protocjar.Protoc.runProtoc(Protoc.java:55)
	at com.github.os72.protocjar.Protoc.main(Protoc.java:43)
java.lang.IllegalArgumentException: Unsupported version: -v2.6.1-SNAPSHOT
	at com.github.os72.protocjar.ProtocVersion.getVersion(ProtocVersion.java:31)
	at com.github.os72.protocjar.Protoc.getVersion(Protoc.java:305)
	at com.github.os72.protocjar.Protoc.runProtoc(Protoc.java:55)
	at com.github.os72.protocjar.Protoc.main(Protoc.java:43)

/tmp/protoc-jar  master ✗                                                                                                                                                                                                                                               17d ◒  
▶ for version in 2.4.1 2.5.0 2.6.1; do                           
java -jar target/protoc-jar-3.4.0.1-SNAPSHOT.jar --version -v"${version}"
done;
protoc-jar: protoc version: 241, detected platform: freebsd/amd64
protoc-jar: protoc version: 241, detected platform: freebsd/amd64
java.io.IOException: Unsupported platform: freebsd/amd64
	at com.github.os72.protocjar.Protoc.extractProtoc(Protoc.java:193)
	at com.github.os72.protocjar.Protoc.extractProtoc(Protoc.java:169)
	at com.github.os72.protocjar.Protoc.runProtoc(Protoc.java:67)
	at com.github.os72.protocjar.Protoc.main(Protoc.java:43)
protoc-jar: protoc version: 250, detected platform: freebsd/amd64
protoc-jar: protoc version: 250, detected platform: freebsd/amd64
java.io.IOException: Unsupported platform: freebsd/amd64
	at com.github.os72.protocjar.Protoc.extractProtoc(Protoc.java:193)
	at com.github.os72.protocjar.Protoc.extractProtoc(Protoc.java:169)
	at com.github.os72.protocjar.Protoc.runProtoc(Protoc.java:67)
	at com.github.os72.protocjar.Protoc.main(Protoc.java:43)
protoc-jar: protoc version: 261, detected platform: freebsd/amd64
protoc-jar: protoc version: 261, detected platform: freebsd/amd64
java.io.IOException: Unsupported platform: freebsd/amd64
	at com.github.os72.protocjar.Protoc.extractProtoc(Protoc.java:193)
	at com.github.os72.protocjar.Protoc.extractProtoc(Protoc.java:169)
	at com.github.os72.protocjar.Protoc.runProtoc(Protoc.java:67)
	at com.github.os72.protocjar.Protoc.main(Protoc.java:43)
```

**Comment by kjopek** [comment]
It seems to be working:
```
java -jar target/protoc-jar-3.4.0.1-SNAPSHOT.jar --version -v"${version}"-SNAPSHOT
done;
protoc-jar: protoc version: 2.4.1-SNAPSHOT, detected platform: freebsd-x86_64 (freebsd/amd64)
protoc-jar: downloading: https://oss.sonatype.org/content/repositories/snapshots/com/github/os72/protoc/2.4.1-SNAPSHOT/maven-metadata.xml
protoc-jar: cached: /tmp/protocjar.webcache/com/github/os72/protoc/2.4.1-SNAPSHOT/maven-metadata.xml
protoc-jar: downloading: https://oss.sonatype.org/content/repositories/snapshots/com/github/os72/protoc/2.4.1-SNAPSHOT/protoc-2.4.1-20170922.183226-5-freebsd-x86_64.exe
protoc-jar: cached: /tmp/protocjar.webcache/com/github/os72/protoc/2.4.1-SNAPSHOT/protoc-2.4.1-20170922.183226-5-freebsd-x86_64.exe
protoc-jar: executing: [/tmp/protocjar2506248276738298707/bin/protoc.exe, --version]
libprotoc 2.4.1
protoc-jar: protoc version: 2.5.0-SNAPSHOT, detected platform: freebsd-x86_64 (freebsd/amd64)
protoc-jar: downloading: https://oss.sonatype.org/content/repositories/snapshots/com/github/os72/protoc/2.5.0-SNAPSHOT/maven-metadata.xml
protoc-jar: cached: /tmp/protocjar.webcache/com/github/os72/protoc/2.5.0-SNAPSHOT/maven-metadata.xml
protoc-jar: downloading: https://oss.sonatype.org/content/repositories/snapshots/com/github/os72/protoc/2.5.0-SNAPSHOT/protoc-2.5.0-20170922.183300-2-freebsd-x86_64.exe
protoc-jar: cached: /tmp/protocjar.webcache/com/github/os72/protoc/2.5.0-SNAPSHOT/protoc-2.5.0-20170922.183300-2-freebsd-x86_64.exe
protoc-jar: executing: [/tmp/protocjar8954064333664302907/bin/protoc.exe, --version]
libprotoc 2.5.0
protoc-jar: protoc version: 2.6.1-SNAPSHOT, detected platform: freebsd-x86_64 (freebsd/amd64)
protoc-jar: downloading: https://oss.sonatype.org/content/repositories/snapshots/com/github/os72/protoc/2.6.1-SNAPSHOT/maven-metadata.xml
protoc-jar: cached: /tmp/protocjar.webcache/com/github/os72/protoc/2.6.1-SNAPSHOT/maven-metadata.xml
protoc-jar: downloading: https://oss.sonatype.org/content/repositories/snapshots/com/github/os72/protoc/2.6.1-SNAPSHOT/protoc-2.6.1-20170922.183408-2-freebsd-x86_64.exe
protoc-jar: cached: /tmp/protocjar.webcache/com/github/os72/protoc/2.6.1-SNAPSHOT/protoc-2.6.1-20170922.183408-2-freebsd-x86_64.exe
protoc-jar: executing: [/tmp/protocjar1194086942426294769/bin/protoc.exe, --version]
libprotoc 2.6.1
```

**Comment by os72** [comment]
Thank you. Also made some small changes to tests

**Comment by os72** [comment]
Released binaries to maven central, it should work without -SNAPSHOT now. Will release the JAR soon
http://central.maven.org/maven2/com/github/os72/protoc/

**Comment by os72** [comment]
Released protoc-jar-3.4.0.1, protoc-jar-maven-plugin-3.4.0.1

**Pull request merged**
