### PR TITLE
Added binaries for ppc64le for v2.4.1, v2.5.0 and v.2.6.1

### PR DESCRIPTION
**Pull request by nakul02**

### CODE REVIEW

**Comment by nakul02** [comment]
Instructions [here](https://issues.apache.org/jira/browse/SYSTEMML-1875).
Ping @bertholdreinwald, @niketanpansare

**Comment by os72** [comment]
Thanks. Please expect the PPC binaries to be unbundled but auto-downloaded. Will need a bit of time for the new feature

**Comment by os72** [comment]
Hi again. Would you be able to test this branch?
https://github.com/os72/protoc-jar/tree/support_unbundled

It should auto-download the PPC binaries from my sonatype snapshots:
https://oss.sonatype.org/content/repositories/snapshots/com/github/os72/protoc/

```
$ java -jar target/protoc-jar-3.4.0.1-SNAPSHOT.jar --version -v2.4.1-SNAPSHOT
protoc-jar: protoc version: 2.4.1-SNAPSHOT, detected platform: windows-x86_64 (windows 8.1/amd64)
protoc-jar: downloading: https://oss.sonatype.org/content/repositories/snapshots/com/github/os72/protoc/2.4.1-SNAPSHOT/maven-metadata.xml
protoc-jar: cached: C:\cygwin64\tmp\protocjar.webcache\com\github\os72\protoc\2.4.1-SNAPSHOT\maven-metadata.xml
protoc-jar: cached: C:\cygwin64\tmp\protocjar.webcache\com\github\os72\protoc\2.4.1-SNAPSHOT\protoc-2.4.1-20170919.042526-3-windows-x86_64.exe
protoc-jar: executing: [C:\cygwin64\tmp\protocjar45868591624127843\bin\protoc.exe, --version]
libprotoc 2.4.1
```

If this works I would promote your PPC binaries to release versions on maven central (instead of embedding them)

And protoc-jar would scan maven central (google protoc, then os72 protoc) for whatever platform/version it cannot satisfy from embedded binaries. This way we don't have to bundle everything all the time

**Comment by nakul02** [comment]
It works 👍
```
➜  protoc-jar git:(support_unbundled) ✗ java -jar target/protoc-jar-3.4.0.1-SNAPSHOT.jar --version -v2.4.1-SNAPSHOT
protoc-jar: protoc version: 2.4.1-SNAPSHOT, detected platform: linux-ppcle_64 (linux/ppc64le)
protoc-jar: downloading: https://oss.sonatype.org/content/repositories/snapshots/com/github/os72/protoc/2.4.1-SNAPSHOT/maven-metadata.xml
protoc-jar: cached: /tmp/protocjar.webcache/com/github/os72/protoc/2.4.1-SNAPSHOT/maven-metadata.xml
protoc-jar: downloading: https://oss.sonatype.org/content/repositories/snapshots/com/github/os72/protoc/2.4.1-SNAPSHOT/protoc-2.4.1-20170919.042526-3-linux-ppcle_64.exe
protoc-jar: cached: /tmp/protocjar.webcache/com/github/os72/protoc/2.4.1-SNAPSHOT/protoc-2.4.1-20170919.042526-3-linux-ppcle_64.exe
protoc-jar: executing: [/tmp/protocjar4225700600077266848/bin/protoc.exe, --version]
libprotoc 2.4.1
➜  protoc-jar git:(support_unbundled) ✗ java -jar target/protoc-jar-3.4.0.1-SNAPSHOT.jar --version -v2.5.0-SNAPSHOT
protoc-jar: protoc version: 2.5.0-SNAPSHOT, detected platform: linux-ppcle_64 (linux/ppc64le)
protoc-jar: downloading: https://oss.sonatype.org/content/repositories/snapshots/com/github/os72/protoc/2.5.0-SNAPSHOT/maven-metadata.xml
protoc-jar: cached: /tmp/protocjar.webcache/com/github/os72/protoc/2.5.0-SNAPSHOT/maven-metadata.xml
protoc-jar: downloading: https://oss.sonatype.org/content/repositories/snapshots/com/github/os72/protoc/2.5.0-SNAPSHOT/protoc-2.5.0-20170919.011703-1-linux-ppcle_64.exe
protoc-jar: cached: /tmp/protocjar.webcache/com/github/os72/protoc/2.5.0-SNAPSHOT/protoc-2.5.0-20170919.011703-1-linux-ppcle_64.exe
protoc-jar: executing: [/tmp/protocjar972692676565978405/bin/protoc.exe, --version]
libprotoc 2.5.0
➜  protoc-jar git:(support_unbundled) ✗ java -jar target/protoc-jar-3.4.0.1-SNAPSHOT.jar --version -v2.6.1-SNAPSHOT
protoc-jar: protoc version: 2.6.1-SNAPSHOT, detected platform: linux-ppcle_64 (linux/ppc64le)
protoc-jar: downloading: https://oss.sonatype.org/content/repositories/snapshots/com/github/os72/protoc/2.6.1-SNAPSHOT/maven-metadata.xml
protoc-jar: cached: /tmp/protocjar.webcache/com/github/os72/protoc/2.6.1-SNAPSHOT/maven-metadata.xml
protoc-jar: downloading: https://oss.sonatype.org/content/repositories/snapshots/com/github/os72/protoc/2.6.1-SNAPSHOT/protoc-2.6.1-20170919.042550-1-linux-ppcle_64.exe
protoc-jar: cached: /tmp/protocjar.webcache/com/github/os72/protoc/2.6.1-SNAPSHOT/protoc-2.6.1-20170919.042550-1-linux-ppcle_64.exe
protoc-jar: executing: [/tmp/protocjar1632344864869914959/bin/protoc.exe, --version]
libprotoc 2.6.1
➜  protoc-jar git:(support_unbundled) ✗ java -jar target/protoc-jar-3.4.0.1-SNAPSHOT.jar --version -v3.4.0-SNAPSHOT
protoc-jar: protoc version: 3.4.0-SNAPSHOT, detected platform: linux-ppcle_64 (linux/ppc64le)
protoc-jar: downloading: https://oss.sonatype.org/content/repositories/snapshots/com/github/os72/protoc/3.4.0-SNAPSHOT/maven-metadata.xml
protoc-jar: cached: /tmp/protocjar.webcache/com/github/os72/protoc/3.4.0-SNAPSHOT/maven-metadata.xml
protoc-jar: downloading: https://oss.sonatype.org/content/repositories/snapshots/com/github/os72/protoc/3.4.0-SNAPSHOT/protoc-3.4.0-20170919.042631-1-linux-ppcle_64.exe
protoc-jar: cached: /tmp/protocjar.webcache/com/github/os72/protoc/3.4.0-SNAPSHOT/protoc-3.4.0-20170919.042631-1-linux-ppcle_64.exe
protoc-jar: executing: [/tmp/protocjar2574288073611823420/bin/protoc.exe, --version]
libprotoc 3.4.0
```

**Comment by os72** [comment]
Great! Will ask for one more test after release. Thanks!

**Comment by os72** [comment]
Released protoc-jar-3.4.0.1, protoc-jar-maven-plugin-3.4.0.1

**Comment by nakul02** [comment]
Thanks @os72!

**Comment by os72** [comment]
Note the PPC binaries are published to maven central:
http://central.maven.org/maven2/com/github/os72/protoc/

**Pull request merged**
