### PR TITLE
Added protobuf ppc64le and 64 & 32 bit versions of protobuf 3.4.0

### PR DESCRIPTION
**Pull request by nakul02**
I contribute to [Apache SystemML](https://github.com/apache/systemml) which [uses](https://github.com/apache/systemml/blob/master/pom.xml#L350) the the associated [maven plugin](https://github.com/os72/protoc-jar-maven-plugin). When trying to build SystemML from source on a Power8 machine, I realized the need for a `ppc64le` build of `protoc`. Hence this PR.

I've added the binaries built with `./configure --disable-shared` & `make install-strip` for `ppcle64` on a POWER8 machines. (this results in a 3.5MB binary, down from a 45MB binary built with symbols). The PR also contains binaries downloaded from the pre-built binaries that Google provides.

Ping @bertholdreinwald, @niketanpansare

### CODE REVIEW

**Comment by nakul02** [comment]
Are there any other additions needed before you can merge?

**Comment by os72** [comment]
No, looks fine, will merge and make a few small modifications. Thanks

**Comment by os72** [comment]
Could you please run PlatformDetector on your PPC machine, what does it print? (eg, `maven test` in `protoc-jar-maven-plugin`)

**Comment by nakul02** [comment]
When I tried `mvn test` on [protoc-jar-maven-plugin](https://github.com/os72/protoc-jar-maven-plugin), first it complained about protoc-jar-3.4 not being in maven central.
After I `mvn install`-ed `protoc-jar`, and tried again, this is what i got:
```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building protoc-jar-maven-plugin 3.4.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:1.2:enforce (enforce-maven) @ protoc-jar-maven-plugin ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ protoc-jar-maven-plugin ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.0:compile (default-compile) @ protoc-jar-maven-plugin ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /data/bjr/protoc-jar-maven-plugin/target/classes
[INFO] 
[INFO] --- maven-plugin-plugin:3.3:descriptor (default-descriptor) @ protoc-jar-maven-plugin ---
[INFO] Using 'UTF-8' encoding to read mojo metadata.
[INFO] Applying mojo extractor for language: java
[INFO] Mojo extractor for language: java found 1 mojo descriptors.
[INFO] Applying mojo extractor for language: bsh
[INFO] Mojo extractor for language: bsh found 0 mojo descriptors.
[INFO] Applying mojo extractor for language: java-annotations
[INFO] Mojo extractor for language: java-annotations found 0 mojo descriptors.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ protoc-jar-maven-plugin ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /data/bjr/protoc-jar-maven-plugin/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.0:testCompile (default-testCompile) @ protoc-jar-maven-plugin ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ protoc-jar-maven-plugin ---
[INFO] No tests to run.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.908 s
[INFO] Finished at: 2017-08-28T18:42:38+00:00
[INFO] Final Memory: 24M/284M
[INFO] ------------------------------------------------------------------------
```

How do i run the platform detector?

Also, when I ran `mvn install` on `protoc-jar`, tests failed because they couldn't find the `ppc64le` compiled binary for earlier versions of the protobuf compiler:
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.github.os72.protocjar.ProtocTest
protoc-jar: protoc version: 241, detected platform: linux/ppc64le
protoc-jar: protoc version: 241, detected platform: linux/ppc64le
protoc-jar: protoc version: 330, detected platform: linux/ppc64le
protoc-jar: protoc version: 330, detected platform: linux/ppc64le
protoc-jar: protoc version: 241, detected platform: linux/ppc64le
protoc-jar: protoc version: 241, detected platform: linux/ppc64le
protoc-jar: protoc version: com.google.protobuf:protoc:3.0.0, detected platform: linux/ppc64le
protoc-jar: downloading: http://central.maven.org/maven2/com/google/protobuf/protoc/3.0.0/protoc-3.0.0-linux-ppcle_64.exe
protoc-jar: protoc version: com.google.protobuf:protoc:3.0.0, detected platform: linux/ppc64le
protoc-jar: downloading: http://central.maven.org/maven2/com/google/protobuf/protoc/3.0.0/protoc-3.0.0-linux-ppcle_64.exe
protoc-jar: protoc version: 261, detected platform: linux/ppc64le
protoc-jar: protoc version: 261, detected platform: linux/ppc64le
Tests run: 5, Failures: 0, Errors: 5, Skipped: 0, Time elapsed: 0.547 sec <<< FAILURE! - in com.github.os72.protocjar.ProtocTest
testRunProtocCompile(com.github.os72.protocjar.ProtocTest)  Time elapsed: 0.037 sec  <<< ERROR!
java.io.FileNotFoundException: bin_241/linux/ppc64le/protoc (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.github.os72.protocjar.Protoc.populateFile(Protoc.java:291)
	at com.github.os72.protocjar.Protoc.extractProtoc(Protoc.java:215)
	at com.github.os72.protocjar.Protoc.extractProtoc(Protoc.java:165)
	at com.github.os72.protocjar.Protoc.runProtoc(Protoc.java:63)
	at com.github.os72.protocjar.ProtocTest.testRunProtocCompile(ProtocTest.java:91)

testRunProtocBasic(com.github.os72.protocjar.ProtocTest)  Time elapsed: 0.002 sec  <<< ERROR!
java.io.FileNotFoundException: bin_330/linux/ppc64le/protoc (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.github.os72.protocjar.Protoc.populateFile(Protoc.java:291)
	at com.github.os72.protocjar.Protoc.extractProtoc(Protoc.java:215)
	at com.github.os72.protocjar.Protoc.extractProtoc(Protoc.java:165)
	at com.github.os72.protocjar.Protoc.runProtoc(Protoc.java:63)
	at com.github.os72.protocjar.ProtocTest.testRunProtocBasic(ProtocTest.java:31)

testRunProtocCompileShade(com.github.os72.protocjar.ProtocTest)  Time elapsed: 0.016 sec  <<< ERROR!
java.io.FileNotFoundException: bin_241/linux/ppc64le/protoc (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.github.os72.protocjar.Protoc.populateFile(Protoc.java:291)
	at com.github.os72.protocjar.Protoc.extractProtoc(Protoc.java:215)
	at com.github.os72.protocjar.Protoc.extractProtoc(Protoc.java:165)
	at com.github.os72.protocjar.Protoc.runProtoc(Protoc.java:63)
	at com.github.os72.protocjar.ProtocTest.testRunProtocCompileShade(ProtocTest.java:101)

testRunProtocDownload(com.github.os72.protocjar.ProtocTest)  Time elapsed: 0.443 sec  <<< ERROR!
java.io.FileNotFoundException: http://central.maven.org/maven2/com/google/protobuf/protoc/3.0.0/protoc-3.0.0-linux-ppcle_64.exe
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1872)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
	at java.net.URL.openStream(URL.java:1045)
	at com.github.os72.protocjar.Protoc.downloadProtoc(Protoc.java:265)
	at com.github.os72.protocjar.Protoc.extractProtoc(Protoc.java:204)
	at com.github.os72.protocjar.Protoc.extractProtoc(Protoc.java:165)
	at com.github.os72.protocjar.Protoc.runProtoc(Protoc.java:63)
	at com.github.os72.protocjar.ProtocTest.testRunProtocDownload(ProtocTest.java:59)

testStdTypes(com.github.os72.protocjar.ProtocTest)  Time elapsed: 0.015 sec  <<< ERROR!
java.io.FileNotFoundException: bin_261/linux/ppc64le/protoc (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at com.github.os72.protocjar.Protoc.populateFile(Protoc.java:291)
	at com.github.os72.protocjar.Protoc.extractProtoc(Protoc.java:215)
	at com.github.os72.protocjar.Protoc.extractProtoc(Protoc.java:165)
	at com.github.os72.protocjar.Protoc.runProtoc(Protoc.java:63)
	at com.github.os72.protocjar.ProtocTest.testStdTypes(ProtocTest.java:69)


Results :

Tests in error: 
  ProtocTest.testRunProtocCompile:91 ? FileNotFound bin_241/linux/ppc64le/protoc...
  ProtocTest.testRunProtocBasic:31 ? FileNotFound bin_330/linux/ppc64le/protoc (...
  ProtocTest.testRunProtocCompileShade:101 ? FileNotFound bin_241/linux/ppc64le/...
  ProtocTest.testRunProtocDownload:59 ? FileNotFound http://central.maven.org/ma...
  ProtocTest.testStdTypes:69 ? FileNotFound bin_261/linux/ppc64le/protoc (No suc...

Tests run: 5, Failures: 0, Errors: 5, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 30.586 s
[INFO] Finished at: 2017-08-28T18:37:39+00:00
[INFO] Final Memory: 25M/291M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project protoc-jar: There are test failures.
[ERROR] 
[ERROR] Please refer to /data/bjr/protoc-jar/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by os72** [comment]
Could you just install SNAPSHOT without tests

**Comment by nakul02** [comment]
Thats what I did for `protoc-jar`: `mvn clean install -DskipTests`
Then in the `protoc-jar-maven-plugin`, I did `mvn test`

**Comment by os72** [comment]
So `mvn test` on `protoc-jar-maven-plugin` will run platform detector and print something

**Comment by nakul02** [comment]
It doesn't seem to have done that. Look at the output I've pasted [above](https://github.com/os72/protoc-jar/pull/27#issuecomment-325443426).

**Comment by os72** [comment]
`mvn clean test` should print something like

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.github.os72.protocjar.maven.DetectorTest
------------------------------------------------------------------------
Detecting the operating system and CPU architecture
------------------------------------------------------------------------
os.detected.name: windows
os.detected.arch: x86_64
os.detected.version: 6.3
os.detected.version.major: 6
os.detected.version.minor: 3
os.detected.classifier: windows-x86_64
{os.detected.version.major=6, os.detected.version=6.3, os.detected.name=windows, os.detected.version.minor=3, os.detected.classifier=windows-x86_64, os.detected.arch=x86_64}
```

**Comment by os72** [comment]
Added this option to protoc-jar. Could you pull latest and try?
```
$ java -jar target/protoc-jar-3.4.0-SNAPSHOT.jar -pp
```

**Comment by os72** [comment]
Released `protoc-jar-3.4.0`.

BTW I'm still interested in the platform detector output. I'm starting to think about reorganizing the binaries and use more downloading vs bundling so we can accommodate more platforms without exploding the jar size..

**Comment by nakul02** [comment]
Sorry, I missed your previous post.
Here it is

```
------------------------------------------------------------------------
Detecting the operating system and CPU architecture
------------------------------------------------------------------------
os.detected.name: linux
os.detected.arch: ppcle_64
os.detected.version: 4.4
os.detected.version.major: 4
os.detected.version.minor: 4
os.detected.release: ubuntu
os.detected.release.version: 16.04
os.detected.release.like.ubuntu: true
os.detected.release.like.debian: true
os.detected.classifier: linux-ppcle_64
```

**Comment by os72** [comment]
Thanks!

**Comment by nakul02** [comment]
One other thing. 
I will have to open a new PR with protoc compiled for ppc64le for versions 2.4.1, 2.5, 2.6.1.
The reason for this is that SystemML uses protoc to compiler caffe protobuf files written for protobuff v2. 
Also, some of the tests won't fail anymore :)

**Comment by os72** [comment]
OK. I may use this opportunity to set up the protoc binary repo for more exotic platforms, and host the PPC builds there. Hope you'll be able to help me test it?

**Pull request merged**
