### PR TITLE
Added Solaris x64 support

### PR DESCRIPTION
**Pull request by siepkes**
Created and added protoc binaries for all protobuf versions for Solaris x64. Binaries were compiled on SmartOS (Illumos) with GCC 4.9 (pkgsrc). They should also work on 'normal' Solaris provided the GCC Runtime libraries are present.

Binaries are build with the following flags:

 * --disable-shared
 * --enable-static
 * --enable-64bit-solaris

### CODE REVIEW

**Comment by os72** [comment]
Thanks! Are the binaries stripped?

**Comment by siepkes** [comment]
Would you believe me if I said yes? ;-) Missed that, sorry! I've updated the binaries with stripped versions.

I added the Solaris binaries and an entry in the POM for each version. I believe that is all there is to it. Or do I need to add some other things to make this PR complete?

**Comment by os72** [comment]
Yes the changes look OK, thanks. Will push to sonatype snapshots first so we can test

**Comment by os72** [comment]
Pushed to snapshots. Could you give it a try (on Solaris):
`java -jar protoc-jar-3.6.0.jar -v<version>-SNAPSHOT --version`
(Example: `java -jar protoc-jar-3.6.0.jar -v3.6.0-SNAPSHOT --version`)

**Comment by siepkes** [comment]
@os72 I've tested all the versions and they seem to work correctly:

```
# java -jar protoc-jar-3.6.0.jar -v3.6.0-SNAPSHOT --version
protoc-jar: protoc version: 3.6.0-SNAPSHOT, detected platform: sunos-x86_64 (sunos/amd64)
protoc-jar: downloading: https://oss.sonatype.org/content/repositories/snapshots/com/github/os72/protoc/3.6.0-SNAPSHOT/maven-metadata.xml
protoc-jar: saved: /var/tmp/protocjar.webcache/com/github/os72/protoc/3.6.0-SNAPSHOT/maven-metadata.xml
protoc-jar: downloading: https://oss.sonatype.org/content/repositories/snapshots/com/github/os72/protoc/3.6.0-SNAPSHOT/protoc-3.6.0-20180823.053326-2-sunos-x86_64.exe
protoc-jar: saved: /var/tmp/protocjar.webcache/com/github/os72/protoc/3.6.0-SNAPSHOT/protoc-3.6.0-20180823.053326-2-sunos-x86_64.exe
protoc-jar: executing: [/var/tmp/protocjar4689410137715227817/bin/protoc.exe, --version]
libprotoc 3.6.0
```

```
$ java -jar protoc-jar-3.6.0.jar -v3.5.1-SNAPSHOT --version
protoc-jar: protoc version: 3.5.1-SNAPSHOT, detected platform: sunos-x86_64 (sunos/amd64)
protoc-jar: downloading: https://oss.sonatype.org/content/repositories/snapshots/com/github/os72/protoc/3.5.1-SNAPSHOT/maven-metadata.xml
protoc-jar: saved: /var/tmp/protocjar.webcache/com/github/os72/protoc/3.5.1-SNAPSHOT/maven-metadata.xml
protoc-jar: downloading: https://oss.sonatype.org/content/repositories/snapshots/com/github/os72/protoc/3.5.1-SNAPSHOT/protoc-3.5.1-20180823.053229-2-sunos-x86_64.exe
protoc-jar: saved: /var/tmp/protocjar.webcache/com/github/os72/protoc/3.5.1-SNAPSHOT/protoc-3.5.1-20180823.053229-2-sunos-x86_64.exe
protoc-jar: executing: [/var/tmp/protocjar5020057252040431211/bin/protoc.exe, --version]
libprotoc 3.5.1
```

```
$ java -jar protoc-jar-3.6.0.jar -v3.5.0-SNAPSHOT --version
protoc-jar: protoc version: 3.5.0-SNAPSHOT, detected platform: sunos-x86_64 (sunos/amd64)
protoc-jar: downloading: https://oss.sonatype.org/content/repositories/snapshots/com/github/os72/protoc/3.5.0-SNAPSHOT/maven-metadata.xml
protoc-jar: saved: /var/tmp/protocjar.webcache/com/github/os72/protoc/3.5.0-SNAPSHOT/maven-metadata.xml
protoc-jar: downloading: https://oss.sonatype.org/content/repositories/snapshots/com/github/os72/protoc/3.5.0-SNAPSHOT/protoc-3.5.0-20180823.053131-2-sunos-x86_64.exe
protoc-jar: saved: /var/tmp/protocjar.webcache/com/github/os72/protoc/3.5.0-SNAPSHOT/protoc-3.5.0-20180823.053131-2-sunos-x86_64.exe
protoc-jar: executing: [/var/tmp/protocjar8353729660990806477/bin/protoc.exe, --version]
libprotoc 3.5.0
```

```
$ java -jar protoc-jar-3.6.0.jar -v3.4.0-SNAPSHOT --version
protoc-jar: protoc version: 3.4.0-SNAPSHOT, detected platform: sunos-x86_64 (sunos/amd64)
protoc-jar: downloading: https://oss.sonatype.org/content/repositories/snapshots/com/github/os72/protoc/3.4.0-SNAPSHOT/maven-metadata.xml
protoc-jar: saved: /var/tmp/protocjar.webcache/com/github/os72/protoc/3.4.0-SNAPSHOT/maven-metadata.xml
protoc-jar: downloading: https://oss.sonatype.org/content/repositories/snapshots/com/github/os72/protoc/3.4.0-SNAPSHOT/protoc-3.4.0-20180823.053021-5-sunos-x86_64.exe
protoc-jar: saved: /var/tmp/protocjar.webcache/com/github/os72/protoc/3.4.0-SNAPSHOT/protoc-3.4.0-20180823.053021-5-sunos-x86_64.exe
protoc-jar: executing: [/var/tmp/protocjar8942245746921156775/bin/protoc.exe, --version]
libprotoc 3.4.0
```

```
$ java -jar protoc-jar-3.6.0.jar -v2.6.1-SNAPSHOT --version
protoc-jar: protoc version: 2.6.1-SNAPSHOT, detected platform: sunos-x86_64 (sunos/amd64)
protoc-jar: downloading: https://oss.sonatype.org/content/repositories/snapshots/com/github/os72/protoc/2.6.1-SNAPSHOT/maven-metadata.xml
protoc-jar: saved: /var/tmp/protocjar.webcache/com/github/os72/protoc/2.6.1-SNAPSHOT/maven-metadata.xml
protoc-jar: downloading: https://oss.sonatype.org/content/repositories/snapshots/com/github/os72/protoc/2.6.1-SNAPSHOT/protoc-2.6.1-20180823.052940-4-sunos-x86_64.exe
protoc-jar: saved: /var/tmp/protocjar.webcache/com/github/os72/protoc/2.6.1-SNAPSHOT/protoc-2.6.1-20180823.052940-4-sunos-x86_64.exe
protoc-jar: executing: [/var/tmp/protocjar2722378583592209653/bin/protoc.exe, --version]
libprotoc 2.6.1
```

```
$ java -jar protoc-jar-3.6.0.jar -v2.5.0-SNAPSHOT --version
protoc-jar: protoc version: 2.5.0-SNAPSHOT, detected platform: sunos-x86_64 (sunos/amd64)
protoc-jar: downloading: https://oss.sonatype.org/content/repositories/snapshots/com/github/os72/protoc/2.5.0-SNAPSHOT/maven-metadata.xml
protoc-jar: saved: /var/tmp/protocjar.webcache/com/github/os72/protoc/2.5.0-SNAPSHOT/maven-metadata.xml
protoc-jar: downloading: https://oss.sonatype.org/content/repositories/snapshots/com/github/os72/protoc/2.5.0-SNAPSHOT/protoc-2.5.0-20180823.052611-3-sunos-x86_64.exe
protoc-jar: saved: /var/tmp/protocjar.webcache/com/github/os72/protoc/2.5.0-SNAPSHOT/protoc-2.5.0-20180823.052611-3-sunos-x86_64.exe
protoc-jar: executing: [/var/tmp/protocjar5619733185574488298/bin/protoc.exe, --version]
libprotoc 2.5.0
```

```
$ java -jar protoc-jar-3.6.0.jar -v2.4.1-SNAPSHOT --version
protoc-jar: protoc version: 2.4.1-SNAPSHOT, detected platform: sunos-x86_64 (sunos/amd64)
protoc-jar: downloading: https://oss.sonatype.org/content/repositories/snapshots/com/github/os72/protoc/2.4.1-SNAPSHOT/maven-metadata.xml
protoc-jar: saved: /var/tmp/protocjar.webcache/com/github/os72/protoc/2.4.1-SNAPSHOT/maven-metadata.xml
protoc-jar: downloading: https://oss.sonatype.org/content/repositories/snapshots/com/github/os72/protoc/2.4.1-SNAPSHOT/protoc-2.4.1-20180823.052533-7-sunos-x86_64.exe
protoc-jar: saved: /var/tmp/protocjar.webcache/com/github/os72/protoc/2.4.1-SNAPSHOT/protoc-2.4.1-20180823.052533-7-sunos-x86_64.exe
protoc-jar: executing: [/var/tmp/protocjar8964238061910196030/bin/protoc.exe, --version]
libprotoc 2.4.1

```

**Comment by os72** [comment]
Great! Will release to maven central next, stay tuned

**Comment by siepkes** [comment]
That would be awesome! Thanks!

**Comment by os72** [comment]
sunos-x86_64 binaries are released; it should work without `-SNAPSHOT` now. Thanks

**Comment by siepkes** [comment]
Verified and works! Thanks!

```
$ java -jar protoc-jar-3.6.0.jar -v3.5.1 --version
protoc-jar: protoc version: 3.5.1, detected platform: sunos-x86_64 (sunos/amd64)
protoc-jar: cached: /var/tmp/protocjar.webcache/com/google/protobuf/protoc/maven-metadata.xml
protoc-jar: cached: /var/tmp/protocjar.webcache/com/github/os72/protoc/maven-metadata.xml
protoc-jar: cached: /var/tmp/protocjar.webcache/com/github/os72/protoc/3.5.1-build2/protoc-3.5.1-build2-sunos-x86_64.exe
protoc-jar: executing: [/var/tmp/protocjar5064115920559020074/bin/protoc.exe, --version]
```

**Comment by os72** [comment]
OK great! Thanks for the contribution

**Pull request merged**
