### PR TITLE
Package all protoc versions in a single jar.

### PR DESCRIPTION
**Pull request by gseitz**
The version to be used must be specified as the first parameter.
This is based on our discussion in https://github.com/sbt/sbt-protobuf/issues/28.

Unfortunately, the jar file becomes quite large (~5MB) due to the fact that the binaries for all versions are now packaged in it.

Let me know if you need anything changed.

Update: This PR doesn't include the modifications to the README.

### CODE REVIEW

**Comment by os72** [comment]
Thanks, looks good, but I would like to cherry-pick

I was thinking to have the option parser a bit more flexible, position-independent, with options: -v241, -v250, -v261. (I would take care of impl of course)

There is also the possibility to pass the version separately:
Protoc.runProtoc(String version, String[] args)

Would you have a preference one way or another?

**Comment by gseitz** [comment]
Yes, making it position independent makes a lot sense. I just wanted to get
a minimal working thing. For `runProtoc`, passing the version as a separate
parameters also sounds reasonable.

So the main method would extract the position independent version parameter
(and fall back to the latest version in case the parameter is not present),
and pass the version and the arguments to `runProtoc`, yes?

**Comment by os72** [comment]
Turns out runProtoc(String, String[]) is already taken by the protoc command override option: runProtoc(String cmd, String[] args)

So I've just added the args extension: -v241, -v250, -v261
Commit a2ff55bf444aafea4074be9c4e6675fa87793d70

Will this work? Do you mind giving it a try?

**Comment by gseitz** [comment]
Looks good, although I'd prefer version strings like `-v2.6.1`, because
it's both easier when the version number comes from some setting and
doesn't need much manipulation (eg in sbt-protobuf), and it looks nicer in
the log output.

WDYT?

**Comment by os72** [comment]
Done, both supported, and added tests:
2b2acd8ca960739027fd046c52e25677683b5881
d5fb7310c27ec4a9dcef1fb57768efb34521466b

Pls let me know if it works for you

**Comment by gseitz** [comment]
This looks great! I'll give it a try on Monday.

**Comment by gseitz** [comment]
Works great. However, I had to set `appendAssemblyId` to `true`, otherwise I couldn't get the artifact to be packaged up properly.

Cheers

**Comment by os72** [comment]
appendAssemblyId should be false (we don't want ...with-dependencies.jar). I'm on maven3, tried a few versions of assembly plugin, they all work
Anyway, let me make the release, then you can refer to the package
SNAPSHOT is here:
https://oss.sonatype.org/content/repositories/snapshots/com/github/os72/protoc-jar/2.x.5-SNAPSHOT/

**Comment by gseitz** [comment]
Ah, might very well be that I had maven 2. I rarely use maven these days.
Thanks

**Comment by os72** [comment]
I've released 2.x.5, should be on maven central now

**Pull request closed without merging**
