### PR TITLE
Bugfix/recover from permission denied on noexec

### PR DESCRIPTION
**Pull request by sandordargo**
This PR includes the changes described in [this issue ticket](https://github.com/os72/protoc-jar-maven-plugin/issues/39).

### CODE REVIEW

**Comment by os72** [comment]
Thank you. I wonder if we could simplify a bit.. Does following print `false` on your system?

```
File f = File.createTempFile("prefix", "suffix"); f.deleteOnExit();
System.out.println(f.setExecutable(true));
```

**Comment by sandordargo** [comment]
To me that prints `true`. For you?

I'm not sure why you ask it, but I have an idea, so here is the thing. `File.setExecutable()` will only set the executable bit to true. It doesn't care about the underlying mount. Similarly `File.canExecute()` will only check this bit and not the mount. You can easily have executable files, but still you will have a permission denied.

When I was investigating, I granted 777 first on the file, then on the whole directory structure (after having commented out the `f.deleteOnExit()`), still I had permission denied. That's how slowly I found that the problem is with noexec.

Which parts would you like to see simplified?

**Comment by sandordargo** [comment]
For getting the mount properties that was the best idea I got either from colleagues or from stackoverflow. But now I do think about writing a small library to query mounts. Still underneath there will be a process - just like now-, but that's not for this month I think.

**Comment by os72** [comment]
I'd like to have a simple test for this at the beginning and if it fails, switch the temp location. If `setExecutable()` isn't sufficient, we could just attempt the execution. But it's ugly to do that each time (and unnecessary on most platforms)

I also don't like adding all this complexity for a corner case. Perhaps better to have a temp folder override?

**Comment by sandordargo** [comment]
My change comes into place if and only if there was an IOException during execution. No action at all otherwise. Even then, the file'd be copied to a new place and would be executed if and only if /tmp was mounted as noexec.

If you have a look at LinuxProtocRecoverer.attemptToRecover(), before doing anything it tests basic things from the easiest (exception cause) to the most difficult (mount options) to take advantage of short circuiting.

If those three things don't apply we don't do anything - no unnecessary work.

To make it cleaner we could check at least the platform from the catch block of `Protoc.runProtoc()` - as well.

**Comment by os72** [comment]
Let me have a closer look. I mean, I don't think we need all those checks. If execution fails in one location for whatever reason, we switch to alternative

**Comment by os72** [comment]
Turns out temp dir location can be changed, system property java.io.tmpdir. How about that?

```
$ java -Djava.io.tmpdir=. -jar target/protoc-jar-3.3.0.1-SNAPSHOT.jar
protoc-jar: protoc version: 330, detected platform: windows 8/amd64
protoc-jar: executing: [C:\github\protoc-jar\.\protocjar7783982935981426806\bin\protoc.exe]
Missing input file.
```

**Comment by sandordargo** [comment]
I'm fine with your branch, I just made a small pull request in order to remove some unnecessary clatter and to restrict the effects on user.home of a disaster.

**Comment by os72** [comment]
Thanks. But pls see my comment re `protoc-jar-maven-plugin`, it requires changes too, extraction and execution are separate
https://github.com/os72/protoc-jar-maven-plugin/issues/39

**Pull request closed without merging**
